#----------db oracle connection------------
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: system
    password: pass
    driver-class-name: oracle.jdbc.OracleDriver
  # Hibernate ddl auto (create, create-drop, validate, update)
  jpa:
    hibernate:
      ddl-auto: update
  batch:
    jdbc:
      initialize-schema: always

#-------------------------------
# The format used for the keystore. It could be set to JKS in case it is a JKS file
server:
  ssl:
    key-store-type: PKCS12
  # The path to the keystore containing the certificate
    key-store: classpath:keystore/invitation.pk
  # The password used to generate the certificate
    key-store-password: BlankInvitation
  # The alias mapped to the certificate
    key-alias: invitation
  #accept only HTTPS requests
    enabled: true