#----------db oracle connection------------
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: system
    password: pass
    driver-class-name: oracle.jdbc.OracleDriver
  # Hibernate ddl auto (create, create-drop, validate, update)
  jpa:
    hibernate:
      ddl-auto: update
  batch:
    jdbc:
      initialize-schema: always

#-------------------------------